# Build mode, currently supported modes are: release/debug/test.
BUILD_MODE = test

# GNU toolchain
TOOLCHAIN_PREFIX = x86_64-unknown-linux-gnu-
CXX = $(TOOLCHAIN_PREFIX)g++
AS = $(TOOLCHAIN_PREFIX)g++
LD = $(TOOLCHAIN_PREFIX)ld
OBJCOPY = $(TOOLCHAIN_PREFIX)objcopy
OBJDUMP = $(TOOLCHAIN_PREFIX)objdump
STRIP = $(TOOLCHAIN_PREFIX)strip
AR = $(TOOLCHAIN_PREFIX)ar

# Compiler & Linker arguments
CXXFLAGS = 
LDFLAGS = 
