#!/usr/bin/env bash

sourceFile=installTestSuite.cpp

cat > ${sourceFile} << EOF
/*********************************************************************
 * DO NOT EDIT                                                       *
 * This is file generated by the script "GenerateSuiteInstaller.sh"  *
 *********************************************************************/

#include "ut/framework/TestRunner.h"

namespace kernel {

EOF

directoryList=`find . -depth 1 -type d |grep -v svn`
for directory in ${directoryList}; do
	testSuiteName=`basename ${directory} | sed 's/\./_/g'`
	echo "void ${testSuiteName}_installTestSuite(TestRunner&);" >> ${sourceFile}
done

cat >> ${sourceFile} << EOF

void TestRunner::installTestSuite() {
EOF

for directory in ${directoryList}; do
	testSuiteName=`basename ${directory} | sed 's/\./_/g'`
	echo "	${testSuiteName}_installTestSuite(*this);" >> ${sourceFile}
done

cat >> ${sourceFile} << EOF
} /* TestRunner::installTestSuite() */

} /* namespace kernel */
EOF
