#ifndef KERNEL_X64_CONSTANT_H_INCLUDED
#define KERNEL_X64_CONSTANT_H_INCLUDED

#include <DEFINE.h>

BEGIN_DEFINE(kernel)

/* Bits of register CR0 */
DEFINE(CR0_BIT_PAGING, 31)
DEFINE(CR0_BIT_CACHE_DISABLE, 30)
DEFINE(CR0_BIT_NOT_WRITE_THROUGH, 29)
DEFINE(CR0_BIT_ALIGNMENT_MASK, 18)
DEFINE(CR0_BIT_WRITE_PROTECT, 16)
DEFINE(CR0_BIT_NUMERIC_ERROR, 5)
DEFINE(CR0_BIT_EXTENSION_TYPE, 4)
DEFINE(CR0_BIT_TASK_SWITCHED, 3)
DEFINE(CR0_BIT_EMULATION, 2)
DEFINE(CR0_BIT_MONITOR_COPROCESSOR, 1)
DEFINE(CR0_BIT_PROTECTION_ENABLED, 0)

/* Bits of register CR4 */
DEFINE(CR4_BIT_OS_UNMASKED_EXCEPTION_SUPPORT, 10)
DEFINE(CR4_BIT_OS_FXSAVE_FXRSTOR_SUPPORT, 9)
DEFINE(CR4_BIT_PERFORMANCE_MONITORING_COUNTER_ENABLE, 8)
DEFINE(CR4_BIT_PAGE_GLOBAL_ENABLE, 7)
DEFINE(CR4_BIT_MACHINE_CHECK_ENABLE, 6)
DEFINE(CR4_BIT_PHYSICAL_ADDRESS_EXTENSION, 5)
DEFINE(CR4_BIT_PAGE_SIZE_EXTENSION, 4)
DEFINE(CR4_BIT_DEBUGGING_EXTENSION, 3)
DEFINE(CR4_BIT_TIME_STAMP_DISABLE, 2)
DEFINE(CR4_BIT_PROTECTED_MODE_VIRTUAL_INTERRUPTS, 1)
DEFINE(CR4_BIT_VIRUTAL_8086_MODE_EXTENSION, 0)

/* Bits of register EFER */
DEFINE(EFER_BIT_FAST_FXSAVE_FXRSTOR, 14)
DEFINE(EFER_BIT_LONG_MODE_SEGMENT_LIMIT_ENABLE, 13)
DEFINE(EFER_BIT_SECURE_VIRTUAL_MACHINE_ENABLE, 12)
DEFINE(EFER_BIT_NO_EXECUTE_ENABLE, 11)
DEFINE(EFER_BIT_LONG_MODE_ACTIVE, 10)
DEFINE(EFER_BIT_LONG_MODE_ENABLE, 8)
DEFINE(EFER_BIT_SYSTEM_CALL_EXTENSION, 0)

/* MSR */
DEFINE(MSR_EXTENDED_FEATURE_ENABLE_REGISTER, 0x00C0000080)

DEFINE(PAGE_SIZE, 0x1000)

END_DEFINE()

#endif /* KERNEL_X64_CONSTANT_H_INCLUDED */
