# Build mode, currently supported modes are: release/debug/test.
BUILD_MODE = test

# GNU cross toolchain
CROSS_TOOLCHAIN = x86_64-unknown-linux-gnu-
CROSS_CXX = $(CROSS_TOOLCHAIN)g++
CROSS_AS = $(CROSS_TOOLCHAIN)g++
CROSS_LD = $(CROSS_TOOLCHAIN)ld
CROSS_OBJCOPY = $(CROSS_TOOLCHAIN)objcopy
CROSS_OBJDUMP = $(CROSS_TOOLCHAIN)objdump
CROSS_STRIP = $(CROSS_TOOLCHAIN)strip
CROSS_AR = $(CROSS_TOOLCHAIN)ar

NATIVE_CXX = g++

# Compiler & Linker arguments
CROSS_CXXFLAGS = 
CROSS_LDFLAGS = 

NATIVE_CXXFLAGS = -O2
