#ifndef KERNEL_X64_CONSTANT_H_INCLUDED
#define KERNEL_X64_CONSTANT_H_INCLUDED

#include <DEFINE.h>

BEGIN_DEFINE(X64ArchitectureConstant)

/* Bits of register CR0 */
DEFINE(CR0_BIT_PAGING, 31)
DEFINE(CR0_BIT_CACHE_DISABLE, 30)
DEFINE(CR0_BIT_NOT_WRITE_THROUGH, 29)
DEFINE(CR0_BIT_ALIGNMENT_MASK, 18)
DEFINE(CR0_BIT_WRITE_PROTECT, 16)
DEFINE(CR0_BIT_NUMERIC_ERROR, 5)
DEFINE(CR0_BIT_EXTENSION_TYPE, 4)
DEFINE(CR0_BIT_TASK_SWITCHED, 3)
DEFINE(CR0_BIT_EMULATION, 2)
DEFINE(CR0_BIT_MONITOR_COPROCESSOR, 1)
DEFINE(CR0_BIT_PROTECTION_ENABLED, 0)

/* Bits of register CR4 */
DEFINE(CR4_BIT_OS_UNMASKED_EXCEPTION_SUPPORT, 10)
DEFINE(CR4_BIT_OS_FXSAVE_FXRSTOR_SUPPORT, 9)
DEFINE(CR4_BIT_PERFORMANCE_MONITORING_COUNTER_ENABLE, 8)
DEFINE(CR4_BIT_PAGE_GLOBAL_ENABLE, 7)
DEFINE(CR4_BIT_MACHINE_CHECK_ENABLE, 6)
DEFINE(CR4_BIT_PHYSICAL_ADDRESS_EXTENSION, 5)
DEFINE(CR4_BIT_PAGE_SIZE_EXTENSION, 4)
DEFINE(CR4_BIT_DEBUGGING_EXTENSION, 3)
DEFINE(CR4_BIT_TIME_STAMP_DISABLE, 2)
DEFINE(CR4_BIT_PROTECTED_MODE_VIRTUAL_INTERRUPTS, 1)
DEFINE(CR4_BIT_VIRUTAL_8086_MODE_EXTENSION, 0)

/* Bits of register Extended Feature Enable Register */
DEFINE(EFER_BIT_FAST_FXSAVE_FXRSTOR, 14)
DEFINE(EFER_BIT_LONG_MODE_SEGMENT_LIMIT_ENABLE, 13)
DEFINE(EFER_BIT_SECURE_VIRTUAL_MACHINE_ENABLE, 12)
DEFINE(EFER_BIT_NO_EXECUTE_ENABLE, 11)
DEFINE(EFER_BIT_LONG_MODE_ACTIVE, 10)
DEFINE(EFER_BIT_LONG_MODE_ENABLE, 8)
DEFINE(EFER_BIT_SYSTEM_CALL_EXTENSION, 0)

/* Bits of APIC Base Address Register */
DEFINE(ABAR_BIT_APIC_ENABLE, 11)
DEFINE(ABAR_BIT_BOOT_STRAP_CPU_CORE, 8)

/* MSR */
DEFINE(MSR_EXTENDED_FEATURE_ENABLE_REGISTER, 0x00C0000080)
DEFINE(MSR_SYS_TARGET_ADDRESS_REGISTER, 0xC0000081)
DEFINE(MSR_LONG_SYSCALL_TARGET_ADDRESS_REGISTER, 0xC0000082)
DEFINE(MSR_SYSCALL_FLAG_MASK, 0xC0000084)
DEFINE(MSR_APIC_BASE_ADDRES_REGISTER, 0x1b)

/* APIC */
DEFINE(APIC_REGISTER_ID, 0x20)
DEFINE(APIC_REGISTER_VERSION, 0x30)
DEFINE(APIC_REGISTER_TASK_PRIORITY, 0x80)
DEFINE(APIC_REGISTER_ARBITRATION_PRIORITY, 0x90)
DEFINE(APIC_REGISTER_PROCESSOR_PRIORITY, 0xA0)
DEFINE(APIC_REGISTER_END_OF_INTERRUPT, 0xB0)
DEFINE(APIC_REGISTER_REMOTE_READ, 0xC0)
DEFINE(APIC_REGISTER_LOGICAL_DESITINATION, 0xD0)
DEFINE(APIC_REGISTER_DESITINATION_FORMAT, 0xE0)
DEFINE(APIC_REGISTER_SPURIOUS_INTERRUPT_VECTOR, 0xF0)
DEFINE(APIC_REGISTER_ERROR_STATUS, 0x280)
DEFINE(APIC_REGISTER_INTERRUPT_COMMAND_LOW, 0x300)
DEFINE(APIC_REGISTER_INTERRUPT_COMMAND_HIGH, 0x310)
DEFINE(APIC_REGISTER_TIMER_LOCAL_VECTOR_TABLE_ENTRY, 0x320)
DEFINE(APIC_REGISTER_THERMAL_LOCAL_VECTOR_TABLE_ENTRY, 0x330)
DEFINE(APIC_REGISTER_PERFORMANCE_COUNTER_LOCAL_VECTOR_TABLE_ENTRY, 0x340)
DEFINE(APIC_REGISTER_LOCAL_INTERRUPT_ZERO_VECTOR_TABLE_ENTRY, 0x350)
DEFINE(APIC_REGISTER_LOCAL_INTERRUPT_ONE_VECTOR_TABLE_ENTRY, 0x360)
DEFINE(APIC_REGISTER_ERROR_VECTOR_TABLE_ENTRY, 0x370)
DEFINE(APIC_REGISTER_TIMER_INITIAL_COUNT, 0x380)
DEFINE(APIC_REGISTER_TIMER_CURRENT_COUNT, 0x390)
DEFINE(APIC_REGISTER_TIMER_DIVIDE_CONFIGURATION, 0x3E0)
DEFINE(APIC_REGISTER_EXTENDED_APIC_FEATURE, 0x400)
DEFINE(APIC_REGISTER_EXTENDED_APIC_CONTROL, 0x410)
DEFINE(APIC_REGISTER_SPECIFIC_END_OF_INTERRUPT, 0x420)

DEFINE(PAGE_SIZE, 0x1000)

END_DEFINE()

#endif /* KERNEL_X64_CONSTANT_H_INCLUDED */
