#ifndef KERNEL_SEXY_IS_INTEGER_H_INCLUDED
#define KERNEL_SEXY_IS_INTEGER_H_INCLUDED

namespace kernel {

template<typename T>
class IS_INTEGER {
public:
	enum {
		value = 0
	};
};

#define KERNEL_SEXY_SPECIALIZE_IS_INTEGER_VALUE(type) \
	template<> \
	class IS_INTEGER<type> { \
	public: \
		enum { \
			value = 1 \
		}; \
	}

KERNEL_SEXY_SPECIALIZE_IS_INTEGER_VALUE(signed char);
KERNEL_SEXY_SPECIALIZE_IS_INTEGER_VALUE(unsigned char);
KERNEL_SEXY_SPECIALIZE_IS_INTEGER_VALUE(short);
KERNEL_SEXY_SPECIALIZE_IS_INTEGER_VALUE(unsigned short);
KERNEL_SEXY_SPECIALIZE_IS_INTEGER_VALUE(int);
KERNEL_SEXY_SPECIALIZE_IS_INTEGER_VALUE(unsigned int);
KERNEL_SEXY_SPECIALIZE_IS_INTEGER_VALUE(long);
KERNEL_SEXY_SPECIALIZE_IS_INTEGER_VALUE(unsigned long);
KERNEL_SEXY_SPECIALIZE_IS_INTEGER_VALUE(long long);
KERNEL_SEXY_SPECIALIZE_IS_INTEGER_VALUE(unsigned long long);

} /* namespace kernel */

#endif /* KERNEL_SEXY_IS_INTEGER_H_INCLUDED */
