SERVER = $(notdir $(CURDIR))
SERVER_FILE = $(SERVER).elf
USER_LD = $(WONTON)/server/user.ld
CLEAN = $(SERVER_FILE)
LIBS = ../../system/jelly/libjelly.a
REQ_DIR = ../../system/jelly
CXXFLAGS += -I$(WONTON)/system

build: compile ../../system/jelly/build $(SERVER_FILE)

$(SERVER_FILE): $(LIBS) $(ALL_OBJS)
	#  LD $@
	@$(LD) -T $(USER_LD) $(LDFLAGS) $(ALL_OBJS) -o $@
	
dump: $(SERVER_FILE)
	$(OBJDUMP) $^ -d --demangle | less

