#!/usr/bin/env bash

sourceFile="$1"
cat > ${sourceFile} << EOF
/******************************************************************
 * DO NOT EDIT                                                    *
 * This file is generated by shell script "GenerateTestSuite.sh"  *
 ******************************************************************/
 
#include "ut/framework/TestRunner.h"
EOF

testSuiteName=`basename ${PWD}`
for header in `ls *.h`; do
	echo "#include \"ut/testsuite/${testSuiteName}/${header}\"" >> ${sourceFile}
done

functionName=`basename ${sourceFile} | sed 's/\\.cpp$//g'`

cat >> ${sourceFile} << EOF

namespace kernel {

void ${functionName}(TestRunner& runner) {
	static TestSuite testSuite;
	runner.addTestSuite(testSuite, "${testSuiteName}");
EOF

for testCase in `ls *.h`; do
	caseName=`echo ${testCase} | sed s/\.h$//g`
	cat >> ${sourceFile} << EOF
	do {
		static ${caseName} testCase;
		testSuite.addTestCase(testCase, "${caseName}");
	} while (0);
EOF
done

cat >> ${sourceFile} << EOF
}

} /* namespace kernel */
EOF
