#!/usr/bin/env bash

sourcePath="installTestSuite.cpp"
cat > ${sourcePath} << EOF
/**************************************************************
 * DO NOT EDIT                                                *
 * Generated by shell script "GenerateTestSuite.sh"           *
 **************************************************************/
 
#include "ut/framework/TestRunner.h"
EOF

for header in `ls *.h`; do
	echo "#include \"${header}\"" >> ${sourcePath}
done

cat >> ${sourcePath} << EOF

namespace kernel {

void TestRunner::installTestSuite() {
EOF

for testCase in "$@"; do
	caseName=`echo ${testCase} | sed s/\.h$//g`
	cat >> ${sourcePath} << EOF
	do {
		static TestSuite testSuite;
		static ${caseName} testCase;
		addTestSuite(testSuite, "${caseName}");
		testSuite.addTestCase(testCase, "${caseName}");
	} while (0);
EOF
done

cat >> ${sourcePath} << EOF
}

} /* namespace kernel */
EOF
