#ifndef KERNEL_ABI_H_INCLUDED
#define KERNEL_ABI_H_INCLUDED

#include <DEFINE.h>

BEGIN_DEFINE(kernel)

/**
 * !!!!!!!!!!!!!!!
 * !!! Warning !!!
 * !!!!!!!!!!!!!!!
 * If you want to change the KERNEL_VIRTUAL_BASE or KERNEL_PHYSICAL_BASE, make sure you have
 * also changed the corresponding linker scripts.
 */
DEFINE_LONG_LONG(KERNEL_VIRTUAL_BASE, 0xFFFFFF0000000000)
DEFINE(KERNEL_RESERVED_MEMORY, 0x100000)
DEFINE(KERNEL_STACK_SIZE, 0x5000)
DEFINE(KERNEL_STACK_TOP, KERNEL_VIRTUAL_BASE + KERNEL_RESERVED_MEMORY)
DEFINE(KERNEL_PHYSICAL_BASE, KERNEL_STACK_SIZE + KERNEL_RESERVED_MEMORY)

END_DEFINE()

#endif /* KERNEL_ABI_H_INCLUDED */
