#!/usr/bin/env bash

sourcePath="installTestSuite.cpp"
cat > ${sourcePath} << EOF
/**************************************************************
 * DO NOT EDIT                                                *
 * Generated by shell script "GenerateTestSuite.sh"           *
 **************************************************************/
 
#include "ut/framework/TestRunner.h"
EOF

for header in `ls *.h`; do
	echo "#include \"${header}\"" >> ${sourcePath}
done

cat >> ${sourcePath} << EOF

namespace kernel {

void TestRunner::installTestSuite() {
EOF

for testCase in "$@"; do
	testCase=`echo ${testCase} | sed s/\.h$//g`
	echo "	static TestSuite testSuite_${testCase};" >> ${sourcePath}
	echo "	addTestSuite(testSuite_${testCase}, \"${testCase}\");" >> ${sourcePath}
	echo "	static ${testCase} testCase_${testCase};" >> ${sourcePath}
	echo "	testCase_${testCase}.addTestPoint(testSuite_${testCase});" >> ${sourcePath}
done

cat >> ${sourcePath} << EOF
}

} /* namespace kernel */
EOF
